language: ruby
cache: bundler
addons:
  code_climate:
    repo_token: d5d15e35e587177c841e60816e6d93cf79fc7efb80070d71f0f270bbcbff186c
rvm:
  - 2.2.1
before_script:
  - cp config/database.travis.yml config/database.yml
  - psql -c 'create database nvm_photography_api_test;' -U postgres
  - bundle exec rake db:migrate --trace
script:
  - RAILS_ENV=test bundle exec rspec