
test:
	app_key: <%= ENV["DROPBOX_APP_KEY"] %>
	app_secret: <%= ENV["DROPBOX_APP_SECRET"] %>
	access_token: <%= ENV["DROPBOX_ACCESS_TOKEN"] %>
	access_token_secret: <%= ENV["DROPBOX_ACCESS_SECRET"] %>
	user_id: <%= ENV["DROPBOX_USER_ID"] %>
	access_type: "dropbox"
development:
	app_key: <%= ENV["DROPBOX_APP_KEY"] %>
	app_secret: <%= ENV["DROPBOX_APP_SECRET"] %>
	access_token: <%= ENV["DROPBOX_ACCESS_TOKEN"] %>
	access_token_secret: <%= ENV["DROPBOX_ACCESS_SECRET"] %>
	user_id: <%= ENV["DROPBOX_USER_ID"] %>
	access_type: "dropbox"

staging:
	app_key: <%= ENV["DROPBOX_APP_KEY"] %>
	app_secret: <%= ENV["DROPBOX_APP_SECRET"] %>
	access_token: <%= ENV["DROPBOX_ACCESS_TOKEN"] %>
	access_token_secret: <%= ENV["DROPBOX_ACCESS_SECRET"] %>
	user_id: <%= ENV["DROPBOX_USER_ID"] %>
	access_type: "dropbox"

production:
	app_key: <%= ENV["DROPBOX_APP_KEY"] %>
	app_secret: <%= ENV["DROPBOX_APP_SECRET"] %>
	access_token: <%= ENV["DROPBOX_ACCESS_TOKEN"] %>
	access_token_secret: <%= ENV["DROPBOX_ACCESS_SECRET"] %>
	user_id: <%= ENV["DROPBOX_USER_ID"] %>
	access_type: "dropbox"